# Generated by Django 4.1 on 2022-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='definition',
            field=models.TextField(max_length=2000),
        ),
    ]
